encrypt:
  key: APODNU3093r2rbjzxcn09u213asdhy08WRFH

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  application:
    name: s1rates
  profiles:
    active: native
  config:
    import: configserver:http://172.19.200.74:8080/
  cloud:
    config:
      label: master
      username: demoAdmin
      password: demoPassword
