


encrypt:
  key: APODNU3093r2rbjzxcn09u213asdhy08WRFH

spring:
  application:
    name: s1rates
  profiles:
    active: native
  config:
    import: optional:configserver:http://172.23.176.1:8080/
  cloud:
    config:
      label: master
      username: demoAdmin
      password: demoPassword